export const metrics = [
  { value: '600+', label: '简历检索与分析', note: '真实任务' },
  { value: '60+', label: '有效候选人', note: '业务联系' },
  { value: '10+', label: '企业面试', note: '闭环验证' },
  { value: '200+', label: '企业评估指标', note: '规则体系' },
];

export const projects = [
  {
    slug: 'talentflow',
    number: '01',
    flagship: true,
    category: 'AI WORKFLOW · RECRUITMENT',
    title: 'AI 猎头人才寻访工作站',
    shortTitle: 'TalentFlow',
    statement: '让 AI 先完成高重复的信息处理，把判断权留给猎头。',
    summary: '面向真实人才寻访场景，把简历检索、候选人分析、履历优化、推荐报告与企业面试连接成可执行工作流。',
    challenge: '猎头需要反复阅读非结构化简历、对照 JD、整理候选人优势与风险，再为不同沟通阶段生成材料。这些工作高频、耗时，而且输出标准不稳定。',
    solution: '通过 LLM 提取工作经历、教育背景、行业经验和岗位能力，建立候选人评分与匹配机制，并将分析结果继续传递到沟通话术和推荐报告。关键结论仍由人工确认。',
    outcome: '累计完成 600+ 次候选人简历检索与分析，与 60+ 位候选人建立有效业务联系，最终预约 10+ 场真实企业面试，验证最小业务闭环。',
    metrics: [
      { value: '600+', label: '分析任务' },
      { value: '60+', label: '有效联系' },
      { value: '10+', label: '企业面试' },
    ],
    flow: ['简历检索', '信息提取', '岗位匹配', '人工判断', '推荐报告', '企业面试'],
    tags: ['LLM Workflow', 'Resume Parsing', 'Information Extraction', 'Prompt Engineering'],
    accent: 'lime',
  },
  {
    slug: 'enterprise-evaluation',
    number: '02',
    flagship: true,
    category: 'ENTERPRISE DATA · RULE ENGINE',
    title: '企业数字资产智能评估系统',
    shortTitle: 'Enterprise Index',
    statement: '把分散的企业数据，变成可以解释、可以复查的经营判断。',
    summary: '构建覆盖企业经营与数字资产的指标、规则和评分体系，从数据采集一直走到风险识别与结果报告。',
    challenge: '企业工商、知识产权、财税和经营信息分散，数据口径不一致。单一总分既难解释，也容易掩盖高风险或关键缺失指标。',
    solution: '将 200+ 项真实指标标准化并映射到 3 大核心板块、19 个细分类目，通过权重计算、规则判断和异常检测形成分层结果，同时为关键风险设置独立判断规则。',
    outcome: '完成“数据采集 → 指标映射 → 规则计算 → 综合评分 → 风险识别 → 结果报告”的完整产品链路，并规划外部数据接口用于自动补全和验证。',
    metrics: [
      { value: '200+', label: '真实指标' },
      { value: '3', label: '核心板块' },
      { value: '19', label: '细分类目' },
    ],
    flow: ['数据采集', '指标映射', '标准化', '规则计算', '风险识别', '结果报告'],
    tags: ['Rule Engine', 'Enterprise Data', 'Data Standardization', 'API Integration'],
    accent: 'cyan',
  },
  {
    slug: 'project-d',
    number: '03',
    flagship: true,
    category: 'DESKTOP AGENT · PERSONAL AI',
    title: 'Project D AI 智能桌面 Agent',
    shortTitle: 'Project D',
    statement: '让 AI 不只知道你的事情，也能在桌面环境里帮你处理事情。',
    summary: '连接大模型与 Windows 桌面环境，围绕文档、录屏、会议纪要、便签、桌面管理和个人记忆构建可执行助手。',
    challenge: '个人信息散落在文件夹、便签、会议和历史交互里。传统聊天式 AI 无法理解这些长期上下文，也不能直接进入用户的桌面工作流。',
    solution: '将自然语言指令连接到本地工具，建立个人记忆与按需召回机制，并针对文档查找等高频任务缩短操作路径，为持续扩展桌面 Agent 奠定架构基础。',
    outcome: '实现录屏、会议纪要、常用文档检索、便签及桌面辅助管理等能力，形成从对话、记忆到本地工具调用的桌面工作空间原型。',
    metrics: [
      { value: 'Local', label: '桌面工具调用' },
      { value: 'Long', label: '长期记忆' },
      { value: 'Multi', label: '多任务入口' },
    ],
    flow: ['自然语言', '意图路由', '上下文召回', '工具调用', '执行反馈', '记忆沉淀'],
    tags: ['AI Agent', 'Memory', 'Tool Calling', 'Desktop Application'],
    accent: 'violet',
    repo: 'https://github.com/ningfangtianwai-pixel/project-d-desktop',
    image: '/project-d-workspace.png',
  },
  {
    slug: 'content-matrix',
    number: '04',
    category: 'OPERATIONS AUTOMATION',
    title: '企业多平台内容矩阵自动化控制台',
    statement: '把四个平台的内容、账号、数据和潜客线索放进同一条运营链路。',
    summary: '统一处理小红书、抖音、视频号和快手的内容生产、审核、发布与评论线索识别。',
    tags: ['Workflow Automation', 'Multi-platform', 'Lead Detection', 'AI Content'],
    accent: 'orange',
  },
  {
    slug: 'manny-workspace',
    number: '05',
    category: 'PERSONAL PRODUCTIVITY · MCP',
    title: 'Manny Personal Workspace',
    statement: '把信息获取、任务、财务和自动化集中到一个个人工作台。',
    summary: '聚合热点资讯、个人财务、便签、任务与日志，验证“采集 → 处理 → AI 总结 → 自动推送”的个人效率闭环。',
    tags: ['MCP', 'Automation', 'Information Aggregation', 'Task Management'],
    accent: 'blue',
  },
  {
    slug: 'long-term-memory',
    number: '06',
    category: 'CONVERSATIONAL AI · MEMORY',
    title: '长期记忆型 AI 系统',
    statement: '让对话跨越会话，保持连续、个性化和角色一致。',
    summary: '设计多层 Prompt 与长期记忆机制，对重要对话和用户信息进行提取、存储、召回和动态表达控制。',
    tags: ['Conversational AI', 'Memory System', 'Prompt Engineering', 'Context Management'],
    accent: 'rose',
  },
];

export const capabilities = [
  { index: '01', title: 'Frame', zh: '业务拆解', text: '把模糊需求拆成角色、输入、流程、约束和可验证结果。' },
  { index: '02', title: 'Design', zh: '产品设计', text: '定义 MVP、人工确认点、异常路径和长期演进边界。' },
  { index: '03', title: 'Build', zh: '系统实现', text: '组合 LLM、Prompt、Agent、规则引擎、MCP 和本地工具。' },
  { index: '04', title: 'Verify', zh: '真实验证', text: '用业务结果、错误样本和反馈循环判断产品是否真正有效。' },
];
